Rock=[
    {'artis': 'Green Day', 'judul': 'Boulevard of Broken Dreams', 'tahun': '2004'},
    {'artis': 'The White Stripes', 'judul': 'Seven Nation Army', 'tahun': '2003'},
    {'artis': 'Foo Fighters', 'judul': 'The Pretender', 'tahun': '2007'},
    {'artis': 'Linkin Park', 'judul': 'In the End', 'tahun': '2000'},
    {'artis': 'The Black Keys', 'judul': 'Lonely Boy', 'tahun': '2011'},
    {'artis': 'The Killers', 'judul': 'Mr. Brightside', 'tahun': '2003'},
    {'artis': 'Arctic Monkeys', 'judul': 'Do I Wanna Know', 'tahun': '2013'},
    {'artis': 'System of a Down', 'judul': 'Chop Suey!', 'tahun': '2001'},
    {'artis': 'Greta Van Fleet', 'judul': 'Highway Tune', 'tahun': '2017'},
    {'artis': 'Imagine Dragon', 'judul': 'Radioactive', 'tahun': '2012'},
    {'artis': 'Fall Out Boy', 'judul': 'Sugar We are Goin Down', 'tahun': '2005'},
    {'artis': 'The Strokes', 'judul': 'Last Nite', 'tahun': '2001'},
    {'artis': 'Three Days Grace', 'judul': 'I Hate Everthing About You', 'tahun': '2003'},
    {'artis': 'Queens of the Stone Age', 'judul': 'No One Knows', 'tahun': '2002'},
    {'artis': 'Audioslave', 'judul': 'Like a Stone', 'tahun': '2002'},
    {'artis': 'Muse', 'judul': 'Starlight', 'tahun': '2006'},
    {'artis': 'Twenty One Pilots', 'judul': 'Stressed Out', 'tahun': '2015'},
    {'artis': 'Evanescence', 'judul': 'Bring Me to Life', 'tahun': '2003'},
    {'artis': 'Disturbed', 'judul': 'Down with the Sickness', 'tahun': '2000'},
    {'artis': 'Foo Fighters', 'judul': 'Best of You', 'tahun': '2005'},
    {'artis': 'Paramore', 'judul': 'Misery Business', 'tahun': '2007'},
    {'artis': 'Panic! at the Disco', 'judul': 'I Write Sins Not Tragedies', 'tahun': '2006'},
    {'artis': 'Black Veil Brides', 'judul': 'In the End', 'tahun': '2012'},
    {'artis': 'Avenged Sevenfold', 'judul': 'Bet Country', 'tahun': '2005'},
    {'artis': 'Breaking Benjamin', 'judul': 'The Diary of Jane', 'tahun': '2006'},
    {'artis': 'My Chemical Romance', 'judul': 'Welcome to the Black Parade', 'tahun': '2006'},
    {'artis': 'Shinedown', 'judul': 'Second Chance', 'tahun': '2008'},
    {'artis': 'Slipknot', 'judul': 'Duality', 'tahun': '2004'},
    {'artis': 'Papa Roach', 'judul': 'Last Resort', 'tahun': '2000'},
    {'artis': 'Chevelle', 'judul': 'The Red', 'tahun': '2002'},
    {'artis': 'Five Finger Death Punch', 'judul': 'Bad Company', 'tahun': '2009'},
    {'artis': 'Volbeat', 'judul': 'Still Counting', 'tahun': '2008'},
    {'artis': 'Rise Against', 'judul': 'Savior', 'tahun': '2008'},
    {'artis': 'Seether', 'judul': 'Fake It', 'tahun': '2007'},
    {'artis': 'Halestorm', 'judul': 'I Miss the Misery', 'tahun': '2012'},
    {'artis': 'Foo Fighters', 'judul': 'Walk', 'tahun': '2011'},
    {'artis': 'Skillet', 'judul': 'Monster', 'tahun': '2009'},
    {'artis': 'Bullet for My Valentine', 'judul': 'Tears Don\'t Fall', 'tahun': '2005'},
    {'artis': 'Avenged Sevenfold', 'judul': 'Nightmare', 'tahun': '2010'},
    {'artis': 'The Pretty Reckless', 'judul': 'Heaven Knows', 'tahun': '2014'},
    {'artis': 'Godsmack', 'judul': 'I Stand Alone', 'tahun': '2002'},
    {'artis': 'Halestorm', 'judul': 'Love Bites (So Do I)', 'tahun': '2012'},
    {'artis': 'Three Days Grace', 'judul': 'Animal I Have Become', 'tahun': '2006'},
    {'artis': 'Stone Sour', 'judul': 'Through Glass', 'tahun': '2006'},
    {'artis': 'Green Day', 'judul': 'American Idiot', 'tahun': '2004'},
    {'artis': 'Theory of a Deadman', 'judul': 'Bad Girlfriend', 'tahun': '2008'},
    {'artis': 'Slash', 'judul': 'Anastasia', 'tahun': '2012'},
    {'artis': 'Breaking Benjamin', 'judul': 'Breath', 'tahun': '2006'},
    {'artis': 'Bring Me the Horizon', 'judul': 'Throne', 'tahun': '2015'},
    {'artis': 'Pop Evil', 'judul': 'Footsteps', 'tahun': '2014'},
    {'artis': 'Papa Roach', 'judul': 'Getting Away with Murder', 'tahun': '2004'},
    {'artis': 'Chevelle', 'judul': 'Send the Pain Below', 'tahun': '2002'},
    {'artis': 'Seether', 'judul': 'Broken', 'tahun': '2002'},
    {'artis': 'Skillet', 'judul': 'Awake and Alive', 'tahun': '2009'},
    {'artis': 'Foo Fighters', 'judul': 'These Days', 'tahun': '2011'},
    {'artis': 'Five Finger Death Punch', 'judul': 'Wrong Side of Heaven', 'tahun': '2013'},
    {'artis': 'My Chemical Romance', 'judul': 'Helena', 'tahun': '2004'},
    {'artis': 'Shinedown', 'judul': '45', 'tahun': '2003'},
    {'artis': 'Rise Against', 'judul': 'Prayer of the Refugee', 'tahun': '2006'},
    {'artis': 'Puddle of Mudd', 'judul': 'Blurry', 'tahun': '2001'},
    {'artis': 'Avenged Sevenfold', 'judul': 'Almost Easy', 'tahun': '2007'},
    {'artis': 'Evanescene', 'judul': 'My Immortal', 'tahun': '2003'},
    {'artis': 'Three Days Grace', 'judul': 'Never Too Late', 'tahun': '2006'},
    {'artis': 'Stone Sour', 'judul': 'Bother', 'tahun': '2002'},
    {'artis': 'Alter Bridge', 'judul': 'Blackbird', 'tahun': '2007'},
    {'artis': 'Seether', 'judul': 'Remedy', 'tahun': '2005'},
    {'artis': 'Skillet', 'judul': 'Hero', 'tahun': '2009'},
    {'artis': 'Bullet for My Valentine', 'judul': 'Waking the Demon', 'tahun': '2008'},
    {'artis': 'Papa Roach', 'judul': 'Scars', 'tahun': '2004'},
    {'artis': 'Three Days Grace', 'judul': 'Pain', 'tahun': '2006'},
    {'artis': 'Chevelle', 'judul': 'The Clincher', 'tahun': '2004'},
    {'artis': 'Breaking Benjamin', 'judul': 'So Cold', 'tahun': '2004'},
    {'artis': 'Theory of Deadman', 'judul': 'Rx (Medicate)', 'tahun': '2017'},
    {'artis': 'Godsmack', 'judul': 'Awake', 'tahun': '2000'},
    {'artis': 'Red Sun Shining', 'judul': 'Emotionless', 'tahun': '2015'},
    {'artis': 'Volbeat', 'judul': 'A Warrior\'s Call', 'tahun': '2010'},
    {'artis': 'Bad Wolves', 'judul': 'Zombie', 'tahun': '2018'},
    {'artis': 'Three Days Grace', 'judul': 'I Am an Animal', 'tahun': '2009'},
    {'artis': 'Stone Sour', 'judul': 'Absolute Zero', 'tahun': '2012'},
    {'artis': 'Seether', 'judul': 'Gasoline', 'tahun': '2002'},
    {'artis': 'Shinedown', 'judul': 'Save Me', 'tahun': '2005'},
    {'artis': 'My Darkest Days', 'judul': 'Porn Star Dancing', 'tahun': '2010'},
    {'artis': 'Black Stone Cherry', 'judul': 'Lonely Train', 'tahun': '2006'},
    {'artis': 'Avenged Sevenfold', 'judul': 'Hail to the King', 'tahun': '2013'},
    {'artis': 'Papa Roach', 'judul': 'Forever', 'tahun': '2006'},
    {'artis': 'The Pretty Reckless', 'judul': 'Make Me Wanna Die', 'tahun': '2010'},
    {'artis': 'Bring Me the Horizon', 'judul': 'Can You Feel My Heart', 'tahun': '2013'},
    {'artis': 'Slipknot', 'judul': 'Before I Forget', 'tahun': '2004'},
    {'artis': 'Pop Evil', 'judul': 'Trenches', 'tahun': '2013'},
    {'artis': 'Puddle of Mudd', 'judul': 'She Hates Me', 'tahun': '2001'},
    {'artis': 'Three Days Grace', 'judul': 'Riot', 'tahun': '2006'},
    {'artis': 'Skillet', 'judul': 'Whispers in the Dark', 'tahun': '2006'},
    {'artis': 'Seether', 'judul': 'Country Song', 'tahun': '2011'},
    {'artis': 'Papa Roach', 'judul': 'Getting Away with Murder', 'tahun': '2004'},
    {'artis': 'Chevelle', 'judul': 'Send the Pain Below', 'tahun': '2002'},
    {'artis': 'Seether', 'judul': 'Broken', 'tahun': '2002'},
    {'artis': 'Skillet', 'judul': 'Awake and Alive', 'tahun': '2009'},
    {'artis': 'Foo Fighters', 'judul': 'These Days', 'tahun': '2011'},
    {'artis': 'Five Finger Death Punch', 'judul': 'Wrong Side of Heaven', 'tahun': '2013'},
    {'artis': 'My Chemical Romance', 'judul': 'Helena', 'tahun': '2004'},
    {'artis': 'AC/DC', 'judul': 'Shot in the Dark', 'tahun': '2020'},
    {'artis': 'Bring Me the Horizon', 'judul': 'Parasite Eve', 'tahun': '2020'},
    {'artis': 'Five Finger Death Punch', 'judul': 'A Little Bit Off', 'tahun': '2020'},
    {'artis': 'Pop Evil', 'judul': 'Work', 'tahun': '2020'},
    {'artis': 'Seether', 'judul': 'Dangerous', 'tahun': '2020'},
    {'artis': 'Shinedown', 'judul': 'Atlas Falls', 'tahun': '2020'},
    {'artis': 'Three Days Grace', 'judul': 'Somebody That I Used to Know', 'tahun': '2020'},
    {'artis': 'Foo Fighters', 'judul': 'Shame Shame', 'tahun': '2020'},
    {'artis': 'The Pretty Reckless', 'judul': 'Death by Rock and Roll', 'tahun': '2021'},
    {'artis': 'Greta Van Fleet', 'judul': 'Heat Above', 'tahun': '2021'},
    {'artis': 'Architects', 'judul': 'Animals', 'tahun': '2021'},
    {'artis': 'Badflower', 'judul': 'Ghost', 'tahun': '2020'},
    {'artis': 'Evascence', 'judul': 'Use My Voice', 'tahun': '2020'},
    {'artis': 'Royal Blood', 'judul': 'Trouble\'s Coming', 'tahun': '2020'},
    {'artis': 'The Hu', 'judul': 'Wolf Totem (feat. Jacoby Shaddix)', 'tahun': '2020'},
    {'artis': 'Sevendust', 'judul': 'Blood From a Stone', 'tahun': '2020'},
    {'artis': 'Deftones', 'judul': 'Ohms', 'tahun': '2020'},
    {'artis': 'Papa Roach', 'judul': 'The Ending', 'tahun': '2020'},
    {'artis': 'Falling In Reverse', 'judul': 'Popular Monster', 'tahun': '2019'},
    {'artis': 'Machine Gun Kelly', 'judul': 'Bloody Valentine', 'tahun': '2020'},
    {'artis': 'Rise Against', 'judul': 'Nowhere Generation', 'tahun': '2021'},
    {'artis': 'Weezer', 'judul': 'All My Favorite Songs', 'tahun': '2021'},
    {'artis': 'The OFfspring', 'judul': 'Let The Bad Times Roll', 'tahun': '2021'},
    {'artis': 'The Pretty Reckless', 'judul': 'Only Love Can Save Me Now', 'tahun': '2021'},
    {'artis': 'Chevelle', 'judul': 'Self Destructor', 'tahun': '2021'},
    {'artis': 'Architects', 'judul': 'Dead Butterflies', 'tahun': '2021'},
    {'artis': 'Badflower', 'judul': '30', 'tahun': '2020'},
    {'artis': 'Royal Blood', 'judul': 'Typhoons', 'tahun': '2021'},
    {'artis': 'Evanescence', 'judul': 'Better Without You', 'tahun': '2021'},
    {'artis': 'The Hu', 'judul': 'Sad But True', 'tahun': '2020'},
    {'artis': 'Sevendust', 'judul': 'Dying to Live', 'tahun': '2020'},
    {'artis': 'Deftones', 'judul': 'Genesis', 'tahun': '2020'},
    {'artis': 'Papa Roach', 'judul': 'Kill the Noise', 'tahun': '2020'},
    {'artis': 'Falling in Reverse', 'judul': 'The Drug In Me Is Reimagined', 'tahun': '2020'},
    {'artis': 'Machine Gun Kelly', 'judul': 'My Ex\'s Best Friend (feat. Blackbear)', 'tahun': '2020'},
    {'artis': 'Rise Against', 'judul': 'Talking to Ourselves', 'tahun': '2021'},
    {'artis': 'Weezer', 'judul': 'Hero', 'tahun': '2020'},
    {'artis': 'The Offspring', 'judul': 'We Never Have Sex Anymore', 'tahun': '2021'},
    {'artis': 'The Pretty Reckless', 'judul': 'And So It Went (feat. Tom Morello)', 'tahun': '2021'},
    {'artis': 'Chevelle', 'judul': 'Peach', 'tahun': '2021'},
    {'artis': 'Royal Blood', 'judul': 'Limbo', 'tahun': '2021'},
    {'artis': 'Rise Against', 'judul': 'Sudden Urge', 'tahun': '2021'},
    {'artis': 'Chevelle', 'judul': 'Remember When', 'tahun': '2021'},
    {'artis': 'Weezer', 'judul': 'Grapes of Wrath', 'tahun': '2021'},
    {'artis': 'The Pretty Reckeless', 'judul': 'Only Love Can Save Me Now (feat. Matt Cameron and Kim Thayil)', 'tahun': '2021'},
    {'artis': 'The Offspring', 'judul': 'This Is Not Utopia', 'tahun': '2021'},
    {'artis': '', 'judul': '', 'tahun': ''},
    
    
    
]