kpop = [
    {'artis': 'BTS', 'judul': 'Dynamite', 'tahun': 2020},
    {'artis': 'BLACKPINK', 'judul': 'How You Like That', 'tahun': 2020},
    {'artis': 'PSY', 'Judul': 'Gangnam Style', 'tahun': 2012},
    {'artis': 'Twice', 'Judul': 'Fancy', 'tahun': 2019},
    {'artis': 'BLACKPINK', 'Judul': 'Kill This Love', 'tahun': 2019},
    {'artis': 'iKON', 'Judul': 'Love Scenario', 'tahun': 2018},
    {'artis': 'ITZY', 'Judul': 'Not Shy', 'tahun': 2020},
    {'artis': 'BTS', 'Judul': 'Blood Sweet Tears', 'tahun': 2016},
    {'artis': 'Red Velvet', 'Judul': 'Red Flavor', 'tahun': 2017},
    {'artis': 'BTS', 'judul': 'Permission To Dance', 'tahun': 2018},
    {'artis': 'BTS', 'judul': 'Boy With Luv', 'tahun': 2019},
    {'artis': 'BLACKPINK', 'judul': 'DDU-DU DDU-DU', 'tahun': 2018},
    {'artis': 'BTS', 'judul': 'Spring Day', 'tahun': 2017},
    {'artis': 'Girls Generation', 'judul': 'Gee', 'tahun': 2009},
    {'artis': 'BTS', 'judul': 'Mic Drop', 'tahun': 2017},
    {'artis': 'BTS', 'Judul': 'DNA', 'tahun': 2017},
    {'artis': 'BTS', 'judul': 'I Need U', 'tahun': 2015},
    {'artis': 'EXO', 'judul': 'Love Shot', 'tahun': 2018},
    {'artis': 'Red Velvet', 'judul': 'Bad Boy', 'tahun': 2018},
    {'artis': 'ITZY', 'judul': 'Wannabe', 'tahun': 2020},
    {'artis': 'BLACKPINK', 'judul': 'Lovesick Girls', 'tahun': 2020},
    {'artis': 'Chanyeol & punch', 'judul': 'Spring is Gone by Chance', 'tahun': 2016},
    {'artis': 'BTS', 'judul': 'N.O', 'tahun': 2013},
    {'artis': 'TWICE', 'judul': 'Cheer Up', 'tahun': 2016},
    {'artis': 'BTS', 'judul': 'Not Today', 'tahun': 2017},
    {'artis': 'EXO', 'judul': 'Monster', 'tahun': 2016},
    {'artis': 'BTS', 'judul': 'Fire', 'tahun': 2016},
    {'artis': 'IU ft. G-Dragon', 'judul': 'palette', 'tahun': 2017},
    {'artis': 'BTS', 'judul': 'MIC Drop (Steve Aoki Remix)', 'tahun': 2017},
    {'artis': 'Wanna One', 'judul': 'Energetic', 'tahun': 2017},
    {'artis': 'BTS', 'judul': 'Fake Love', 'tahun': 2017},
    {'artis': 'TWICE', 'judul': 'Feel Special', 'tahun': 2019},
    {'artis': 'BLACKPINK', 'judul': 'As If Its Your Last', 'tahun': 2017},
    {'artis': 'Red Velvet', 'judul': 'Psycho', 'tahun': 2019},
    {'artis': 'EXO', 'judul': 'Tempo', 'tahun': 2018},
    {'artis': 'IU', 'judul': 'Blueming', 'tahun': 2019},
    {'artis': 'Stray Kids', 'judul': 'Gods Menu', 'tahun': 2020},
    {'artis': 'MAMAMOO', 'judul': 'Hip', 'tahun': 2019},
    {'artis': 'NCT', 'judul': 'Kick Back', 'tahun': 2021},
    {'artis': 'GOT7', 'judul': 'Just Right', 'tahun': 2015},
    {'artis': 'TWICE', 'judul': 'Likey', 'tahun': 2017},
    {'artis': 'Red Velvet', 'judul': 'Russian Roulette', 'tahun': 2016},
    {'artis': 'EXO', 'judul': 'Ko Ko Bop', 'tahun': 2017},
    {'artis': 'IU', 'judul': 'Good Day', 'tahun': 2010},
    {'artis': 'Stray Kids', 'judul': 'My Pace', 'tahun': 2018},
    {'artis': 'MAMAMOO', 'judul': 'Starry Night', 'tahun': 2018},
    {'artis': 'NCT', 'judul': 'Boss', 'tahun': 2018},
    {'artis': 'GOT7', 'judul': 'Hard Carry', 'tahun': 2016},
    {'artis' : 'BTS', 'judul' : 'Lie', 'tahun' : 2017},
    {'artis' : 'BTS', 'judul' : 'Mama', 'tahun' : 2017},
    {'artis': 'Red Velvet', 'judul': 'Peek A boo', 'tahun': 2017},
    {'artis': 'Red Velvet', 'judul': 'Feel My Rhythm', 'tahun': 2022},
    {'artis': 'Red Velvet', 'judul': 'Queendom', 'tahun': 2021},
    {'artis': 'Red Velvet', 'judul': 'Zim Zalabim', 'tahun': 2019},
    {'artis': 'Red Velvet', 'judul': 'Happiness', 'tahun': 2014},
    {'artis': 'Red Velvet', 'judul': 'you better know', 'tahun': 2017},
    {'artis': 'Red Velvet', 'judul': 'Oh Boy', 'tahun': 2015},
    {'artis': 'Red Velvet', 'judul': 'Power Up', 'tahun': 2018},
    {'artis': 'Red Velvet', 'judul': 'Dumb Dumb ', 'tahun': 2015},
    {'artis': 'Red Velvet', 'judul': 'Would U', 'tahun': 2017},
    {'artis': 'BTS', 'Judul': 'Run', 'tahun': 2022},
    {'artis': 'BTS', 'Judul': 'Dope', 'tahun': 2012},
    {'artis': 'BTS', 'Judul': 'Anpanman', 'tahun': 2018},
    {'artis': 'BTS', 'Judul': 'Where You from', 'tahun': 2014},
    {'artis': 'BTS', 'Judul': 'save me', 'tahun': 2016},
    {'artis': 'BTS', 'Judul': 'Converse High', 'tahun': 2016},
    {'artis': 'BTS', 'Judul': 'Born singer', 'tahun': 2022},
    {'artis': 'BTS', 'Judul': 'lost', 'tahun': 2016},
    {'artis': 'BTS', 'Judul': 'Begin', 'tahun': 2016},
    {'artis': 'BLACKPINK', 'Judul': 'Playing With Fire', 'tahun': 2017},
    {'artis': 'BLACKPINK', 'Judul': 'Boombayah', 'tahun': 2017},
    {'artis': 'BLACKPINK', 'Judul': 'Stay', 'tahun': 2017},
    {'artis': 'BLACKPINK', 'Judul': 'making video', 'tahun': 2017},
    {'artis': 'BLACKPINK', 'Judul': 'Whistle', 'tahun': 2017},
    {'artis': 'BLACKPINK', 'Judul': 'REALLY', 'tahun': 2017},
    {'artis': 'BLACKPINK', 'Judul': 'SEE U LATER', 'tahun': 2018},
    {'artis': 'BLACKPINK', 'Judul': 'KICK IT', 'tahun': 2018},
    {'artis': 'BLACKPINK', 'Judul': 'HOPE NOT', 'tahun': 2018},
    {'artis': 'BLACKPINK', 'Judul': 'FOREVER YOUNG', 'tahun': 2019},
    {'artis': 'BLACKPINK', 'Judul': 'Tally', 'tahun': 2022},
    {'artis': 'BLACKPINK', 'Judul': 'Shut Down', 'tahun': 2022},
    {'artis': 'BLACKPINK', 'Judul': 'Ready For Love', 'tahun': 2022},
    {'artis': 'BLACKPINK', 'Judul': 'The Happiest Girl', 'tahun': 2022},
    {'artis': 'BLACKPINK', 'Judul': 'Playing With Fire', 'tahun': 2017},
    {'artis': 'BLACKPINK', 'Judul': 'Hard To Love', 'tahun': 2022},
    {'artis': 'BLACKPINK', 'Judul': 'Typa girl', 'tahun': 2022},
    {'artis': 'BLACKPINK', 'Judul': 'Yeah Yeah Yeah', 'tahun': 2022},
    {'artis': 'EXO', 'judul': 'Gravity', 'tahun': 2018},
    {'artis': 'EXO', 'judul': 'Sign', 'tahun': 2018},
    {'artis': 'EXO', 'judul': 'Damage', 'tahun': 2018},
    {'artis': 'EXO', 'judul': 'ooh la la', 'tahun': 2018},
    {'artis': 'EXO', 'judul': 'Smile On Face', 'tahun': 2018},
    {'artis': 'EXO', 'judul': 'Touch It', 'tahun': 2017},
    {'artis': 'EXO', 'judul': 'The Eve', 'tahun': 2017},
    {'artis': 'EXO', 'judul': 'Chill', 'tahun': 2017},
    {'artis': 'EXO', 'judul': 'Going Crazy', 'tahun': 2017},
    {'artis': 'EXO', 'judul': 'Diamond', 'tahun': 2017},
    {'artis': 'EXO', 'judul': 'Forever', 'tahun': 2017},
    {'artis': 'EXO', 'judul': 'Walk on Memories', 'tahun': 2017},
    {'artis': 'EXO', 'judul': 'What U Do?', 'tahun': 2017},
    {'artis': 'EXO', 'judul': 'XOXO', 'tahun': 2013},
    {'artis': 'EXO', 'judul': 'Baby dont cry', 'tahun': 2013},
    {'artis': 'EXO', 'judul': 'Dont go', 'tahun': 2013},
    {'artis': 'EXO', 'judul': 'Lucky', 'tahun': 2013},
    {'artis': 'EXO', 'judul': 'No Matter', 'tahun': 2021},
    {'artis': 'EXO', 'judul': 'Paradise', 'tahun': 2021},
    {'artis': 'EXO', 'judul': 'Dont Fight The Feeling', 'tahun': 2021},
    {'artis': 'EXO', 'judul': 'Just As Usual', 'tahun': 2021},
    {'artis': 'EXO', 'judul': 'Runaway', 'tahun': 2013}
]

