kpop = [
    {'artis': 'BTS', 'judul': 'Dynamite', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=gdZLi9oWNZg'},
    {'artis': 'BLACKPINK', 'judul': 'How You Like That', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=ioNng23DkIM'},
    {'artis': 'PSY', 'Judul': 'Gangnam Style', 'tahun': '2012', 'link' : 'https://www.youtube.com/watch?v=9bZkp7q19f0'},
    {'artis': 'Twice', 'Judul': 'Fancy', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=kOHB85vDuow'},
    {'artis': 'BLACKPINK', 'Judul': 'Kill This Love', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=2S24-y0Ij3Y'},
    {'artis': 'iKON', 'Judul': 'Love Scenario', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=vecSVX1QYbQ'},
    {'artis': 'ITZY', 'Judul': 'Not Shy', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=wTowEKjDGkU'},
    {'artis': 'BTS', 'Judul': 'Blood Sweet Tears', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=hmE9f-TEutc'},
    {'artis': 'Red Velvet', 'Judul': 'Red Flavor', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=WyiIGEHQP8o'},
    {'artis': 'BTS', 'judul': 'Permission To Dance', 'tahun': '2018', 'link' :'https://www.youtube.com/watch?v=CuklIb9d3fI'},
    {'artis': 'BTS', 'judul': 'Boy With Luv', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=XsX3ATc3FbA'},
    {'artis': 'BLACKPINK', 'judul': 'DDU-DU DDU-DU', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=IHNzOHi8sJs'},
    {'artis': 'BTS', 'judul': 'Spring Day', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=xEeFrLSkMm8'},
    {'artis': 'Girls Generation', 'judul': 'Gee', 'tahun': '2009', 'link' : 'https://www.youtube.com/watch?v=U7mPqycQ0tQ'},
    {'artis': 'BTS', 'judul': 'Mic Drop', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=kTlv5_Bs8aw'},
    {'artis': 'BTS', 'Judul': 'DNA', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=MBdVXkSdhwU'},
    {'artis': 'BTS', 'judul': 'I Need U', 'tahun': '2015', 'link' : 'https://www.youtube.com/watch?v=jjskoRh8GTE'},
    {'artis': 'EXO', 'judul': 'Love Shot', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=pSudEWBAYRE'},
    {'artis': 'Red Velvet', 'judul': 'Bad Boy', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=J_CFBjAyPWE'},
    {'artis': 'ITZY', 'judul': 'Wannabe', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=fE2h3lGlOsk'},
    {'artis': 'BLACKPINK', 'judul': 'Lovesick Girls', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=dyRsYk0LyA8'},
    {'artis': 'Chanyeol & punch', 'judul': 'Spring is Gone by Chance', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=GjyMuHmzxVE'},
    {'artis': 'BTS', 'judul': 'N.O', 'tahun': '2013', 'link' : 'https://www.youtube.com/watch?v=mmgxPLLLyVo'},
    {'artis': 'TWICE', 'judul': 'Cheer Up', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=c7rCyll5AeY'},
    {'artis': 'BTS', 'judul': 'Not Today', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=9DwzBICPhdM'},
    {'artis': 'EXO', 'judul': 'Monster', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=KSH-FVVtTf0'},
    {'artis': 'BTS', 'judul': 'Fire', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=ALj5MKjy2BU'},
    {'artis': 'IU ft. G-Dragon', 'judul': 'palette', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=d9IxdwEFk1c'},
    {'artis': 'BTS', 'judul': 'MIC Drop (Steve Aoki Remix)', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=kTlv5_Bs8aw'},
    {'artis': 'Wanna One', 'judul': 'Energetic', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=EVaV7AwqBWg'},
    {'artis': 'BTS', 'judul': 'Fake Love', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=7C2z4GqqS5E'},
    {'artis': 'TWICE', 'judul': 'Feel Special', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=3ymwOvzhwHs'},
    {'artis': 'BLACKPINK', 'judul': 'As If Its Your Last', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=Amq-qlqbjYA'},
    {'artis': 'Red Velvet', 'judul': 'Psycho', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=uR8Mrt1IpXg'},
    {'artis': 'EXO', 'judul': 'Tempo', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=iwd8N6K-sLk'},
    {'artis': 'IU', 'judul': 'Blueming', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=D1PvIWdJ8xo'},
    {'artis': 'Stray Kids', 'judul': 'Gods Menu', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=TQTlCHxyuu8'},
    {'artis': 'MAMAMOO', 'judul': 'Hip', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=KhTeiaCezwM'},
    {'artis': 'WAYV', 'judul': 'Kick Back', 'tahun': '2021', 'link' : 'https://www.youtube.com/results?search_query=kick+back+nct'},
    {'artis': 'GOT7', 'judul': 'Just Right', 'tahun': '2015', 'link' : 'https://www.youtube.com/watch?v=vrdk3IGcau8'},
    {'artis': 'TWICE', 'judul': 'Likey', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=V2hlQkVJZhE'},
    {'artis': 'Red Velvet', 'judul': 'Russian Roulette', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=QslJYDX3o8s'},
    {'artis': 'EXO', 'judul': 'Ko Ko Bop', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=IdssuxDdqKk'},
    {'artis': 'IU', 'judul': 'Good Day', 'tahun': '2010', 'link' : 'https://www.youtube.com/watch?v=jeqdYqsrsA0'},
    {'artis': 'Stray Kids', 'judul': 'My Pace', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=pok5yDw77uM'},
    {'artis': 'MAMAMOO', 'judul': 'Starry Night', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=LjUXm0Zy_dk'},
    {'artis': 'NCT', 'judul': 'Boss', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=0AUFyFEt35g'},
    {'artis': 'GOT7', 'judul': 'Hard Carry', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=O57jr1oZDIw'},
    {'artis' : 'BTS', 'judul' : 'Lie', 'tahun' : '2017', 'link' : 'https://www.youtube.com/watch?v=omzjKIgeJGs'},
    {'artis' : 'BTS', 'judul' : 'Mama', 'tahun' : '2017', 'link' : 'https://www.youtube.com/watch?v=nVHcXZK7pKs'},
    {'artis': 'Red Velvet', 'judul': 'Peek A boo', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=6uJf2IT2Zh8'},
    {'artis': 'Red Velvet', 'judul': 'Feel My Rhythm', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=R9At2ICm4LQ'},
    {'artis': 'Red Velvet', 'judul': 'Queendom', 'tahun': '2021', 'link' : 'https://www.youtube.com/watch?v=c9RzZpV460k'},
    {'artis': 'Red Velvet', 'judul': 'Zim Zalabim', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=YBnGBb1wg98'},
    {'artis': 'Red Velvet', 'judul': 'Happiness', 'tahun': '2014', 'link' : 'https://www.youtube.com/watch?v=JFgv8bKfxEs'},
    {'artis': 'Red Velvet', 'judul': 'you better know', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=qF6wlRu9S9E'},
    {'artis': 'Red Velvet', 'judul': 'Oh Boy', 'tahun': '2015', 'link' :'https://www.youtube.com/watch?v=3PgGuUP8_jI'},
    {'artis': 'Red Velvet', 'judul': 'Power Up', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=aiHSVQy9xN8'},
    {'artis': 'Red Velvet', 'judul': 'Dumb Dumb ', 'tahun': '2015', 'link' : 'https://www.youtube.com/watch?v=XGdbaEDVWp0'},
    {'artis': 'Red Velvet', 'judul': 'Would U', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=XGdbaEDVWp0'},
    {'artis': 'BTS', 'Judul': 'Run', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=ssD6mzewGVo'},
    {'artis': 'BTS', 'Judul': 'Dope', 'tahun': '2012', 'link' : 'https://www.youtube.com/watch?v=BVwAVbKYYeM'},
    {'artis': 'BTS', 'Judul': 'Anpanman', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=EFHeeRIDAsg'},
    {'artis': 'BTS', 'Judul': 'Where You from', 'tahun': '2014', 'link' : 'https://www.youtube.com/watch?v=cicyjCWzrRw'},
    {'artis': 'BTS', 'Judul': 'save me', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=GZjt_sA2eso'},
    {'artis': 'BTS', 'Judul': 'Converse High', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=jw-pAvTfPFY'},
    {'artis': 'BTS', 'Judul': 'Born singer', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=TbjUXK2M5n8'},
    {'artis': 'BTS', 'Judul': 'lost', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=-YIj6H4ShQA'},
    {'artis': 'BTS', 'Judul': 'Begin', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=-YIj6H4ShQA'},
    {'artis': 'BLACKPINK', 'Judul': 'Playing With Fire', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=9pdj4iJD08s'},
    {'artis': 'BLACKPINK', 'Judul': 'Boombayah', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=bwmSjveL3Lc'},
    {'artis': 'BLACKPINK', 'Judul': 'Stay', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=FzVR_fymZw4'},
    {'artis': 'BLACKPINK', 'Judul': 'pink venom', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=gQlMMD8auMs'},
    {'artis': 'BLACKPINK', 'Judul': 'Whistle', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=dISNgvVpWlo'},
    {'artis': 'BLACKPINK', 'Judul': 'REALLY', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=He322O1JWgU'},
    {'artis': 'BLACKPINK', 'Judul': 'SEE U LATER', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=fpimnj4SNjQ'},
    {'artis': 'BLACKPINK', 'Judul': 'KICK IT', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=-gZC9hC1PDQ'},
    {'artis': 'BLACKPINK', 'Judul': 'HOPE NOT', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=l6zMnMMzsss'},
    {'artis': 'BLACKPINK', 'Judul': 'FOREVER YOUNG', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=-gibBYpzZbI'},
    {'artis': 'BLACKPINK', 'Judul': 'Tally', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=VQo4hyWfBQ4'},
    {'artis': 'BLACKPINK', 'Judul': 'Shut Down', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=NpVJidAKOqc'},
    {'artis': 'BLACKPINK', 'Judul': 'Ready For Love', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=-Wduzor_Y1Q'},
    {'artis': 'BLACKPINK', 'Judul': 'The Happiest Girl', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=kVXazE8wR1Q'},
    {'artis': 'BLACKPINK', 'Judul': 'ice cream', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=vRXZj0DzXIA' },
    {'artis': 'BLACKPINK', 'Judul': 'Hard To Love', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=7Hr3p1BHC_E'},
    {'artis': 'BLACKPINK', 'Judul': 'Typa girl', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=z9tifvQSu-g'},
    {'artis': 'BLACKPINK', 'Judul': 'Yeah Yeah Yeah', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=wQTjv-Xo1gY'},
    {'artis': 'EXO', 'judul': 'Gravity', 'tahun': '2018'},
    {'artis': 'EXO', 'judul': 'Sign', 'tahun': '2018'},
    {'artis': 'EXO', 'judul': 'Damage', 'tahun': '2018'},
    {'artis': 'EXO', 'judul': 'ooh la la', 'tahun': '2018'},
    {'artis': 'EXO', 'judul': 'Smile On Face', 'tahun': '2018'},
    {'artis': 'EXO', 'judul': 'Touch It', 'tahun': '2017'},
    {'artis': 'EXO', 'judul': 'The Eve', 'tahun': '2017'},
    {'artis': 'EXO', 'judul': 'Chill', 'tahun': '2017'},
    {'artis': 'EXO', 'judul': 'Going Crazy', 'tahun': '2017'},
    {'artis': 'EXO', 'judul': 'Diamond', 'tahun': '2017'},
    {'artis': 'EXO', 'judul': 'Forever', 'tahun': '2017'},
    {'artis': 'EXO', 'judul': 'Walk on Memories', 'tahun': '2017'},
    {'artis': 'EXO', 'judul': 'What U Do?', 'tahun': '2017'},
    {'artis': 'EXO', 'judul': 'XOXO', 'tahun': '2013'},
    {'artis': 'EXO', 'judul': 'Baby dont cry', 'tahun': '2013'},
    {'artis': 'EXO', 'judul': 'Dont go', 'tahun': '2013'},
    {'artis': 'EXO', 'judul': 'Lucky', 'tahun': '2013'},
    {'artis': 'EXO', 'judul': 'No Matter', 'tahun': '2021'},
    {'artis': 'EXO', 'judul': 'Paradise', 'tahun': '2021'},
    {'artis': 'EXO', 'judul': 'Dont Fight The Feeling', 'tahun': '2021'},
    {'artis': 'EXO', 'judul': 'Just As Usual', 'tahun': '2021'},
    {'artis': 'EXO', 'judul': 'Runaway', 'tahun': '2013'}
]
