Rock=[
    {'artis': 'Green Day', 'judul': 'Boulevard of Broken Dreams', 'tahun': '2004'},
    {'artis': 'The White Stripes', 'judul': 'Seven Nation Army', 'tahun': '2003'},
    {'artis': 'Foo Fighters', 'judul': 'The Pretender', 'tahun': '2007'},
    {'artis': 'Linkin Park', 'judul': 'In the End', 'tahun': '2000'},
    {'artis': 'The Black Keys', 'judul': 'Lonely Boy', 'tahun': '2011'},
    {'artis': 'The Killers', 'judul': 'Mr. Brightside', 'tahun': '2003'},
    {'artis': 'Arctic Monkeys', 'judul': 'Do I Wanna Know', 'tahun': '2013'},
    {'artis': 'System of a Down', 'judul': 'Chop Suey!', 'tahun': '2001'},
    {'artis': 'Greta Van Fleet', 'judul': 'Highway Tune', 'tahun': '2017'},
    {'artis': 'Imagine Dragon', 'judul': 'Radioactive', 'tahun': '2012'},
    {'artis': 'Fall Out Boy', 'judul': 'Sugar We are Goin Down', 'tahun': '2005'},
    {'artis': 'The Strokes', 'judul': 'Last Nite', 'tahun': '2001'},
    {'artis': 'Three Days Grace', 'judul': 'I Hate Everthing About You', 'tahun': '2003'},
    {'artis': 'Queens of the Stone Age', 'judul': 'No One Knows', 'tahun': '2002'},
    {'artis': 'Audioslave', 'judul': 'Like a Stone', 'tahun': '2002'},
    {'artis': 'Muse', 'judul': 'Starlight', 'tahun': '2006'},
    {'artis': 'Twenty One Pilots', 'judul': 'Stressed Out', 'tahun': '2015'},
    {'artis': 'Evanescence', 'judul': 'Bring Me to Life', 'tahun': '2003'},
    {'artis': 'Disturbed', 'judul': 'Down with the Sickness', 'tahun': '2000'},
    {'artis': 'Foo Fighters', 'judul': 'Best of You', 'tahun': '2005'},
    {'artis': 'Paramore', 'judul': 'Misery Business', 'tahun': '2007'},
    {'artis': 'Panic! at the Disco', 'judul': 'I Write Sins Not Tragedies', 'tahun': '2006'},
    {'artis': 'Black Veil Brides', 'judul': 'In the End', 'tahun': '2012'},
    {'artis': 'Avenged Sevenfold', 'judul': 'Bet Country', 'tahun': '2005'},
    {'artis': 'Breaking Benjamin', 'judul': 'The Diary of Jane', 'tahun': '2006'},
    {'artis': 'My Chemical Romance', 'judul': 'Welcome to the Black Parade', 'tahun': '2006'},
    {'artis': 'Shinedown', 'judul': 'Second Chance', 'tahun': '2008'},
    {'artis': 'Slipknot', 'judul': 'Duality', 'tahun': '2004'},
    {'artis': 'Papa Roach', 'judul': 'Last Resort', 'tahun': '2000'},
    {'artis': 'Chevelle', 'judul': 'The Red', 'tahun': '2002'},
    {'artis': 'Five Finger Death Punch', 'judul': 'Bad Company', 'tahun': '2009'},
    {'artis': 'Volbeat', 'judul': 'Still Counting', 'tahun': '2008'},
    {'artis': 'Rise Against', 'judul': 'Savior', 'tahun': '2008'},
    {'artis': 'Seether', 'judul': 'Fake It', 'tahun': '2007'},
    {'artis': 'Halestorm', 'judul': 'I Miss the Misery', 'tahun': '2012'},
    {'artis': 'Foo Fighters', 'judul': 'Walk', 'tahun': '2011'},
    {'artis': 'Skillet', 'judul': 'Monster', 'tahun': '2009'},
    {'artis': 'Bullet for My Valentine', 'judul': 'Tears Don\'t Fall', 'tahun': '2005'},
    {'artis': 'Avenged Sevenfold', 'judul': 'Nightmare', 'tahun': '2010'},
    {'artis': 'The Pretty Reckless', 'judul': 'Heaven Knows', 'tahun': '2014'},
    {'artis': 'Godsmack', 'judul': 'I Stand Alone', 'tahun': '2002'},
    {'artis': 'Halestorm', 'judul': 'Love Bites (So Do I)', 'tahun': '2012'},
    {'artis': 'Three Days Grace', 'judul': 'Animal I Have Become', 'tahun': '2006'},
    {'artis': 'Stone Sour', 'judul': 'Through Glass', 'tahun': '2006'},
    {'artis': 'Green Day', 'judul': 'American Idiot', 'tahun': '2004'},
    {'artis': 'Theory of a Deadman', 'judul': 'Bad Girlfriend', 'tahun': '2008'},
    {'artis': 'Slash', 'judul': 'Anastasia', 'tahun': '2012'},
    {'artis': 'Breaking Benjamin', 'judul': 'Breath', 'tahun': '2006'},
    {'artis': 'Bring Me the Horizon', 'judul': 'Throne', 'tahun': '2015'},
    {'artis': 'Pop Evil', 'judul': 'Footsteps', 'tahun': '2014'},
    {'artis': 'Papa Roach', 'judul': 'Getting Away with Murder', 'tahun': '2004'},
    {'artis': 'Chevelle', 'judul': 'Send the Pain Below', 'tahun': '2002'},
    {'artis': 'Seether', 'judul': 'Broken', 'tahun': '2002'},
    {'artis': 'Skillet', 'judul': 'Awake and Alive', 'tahun': '2009'},
    {'artis': 'Foo Fighters', 'judul': 'These Days', 'tahun': '2011'},
    {'artis': 'Five Finger Death Punch', 'judul': 'Wrong Side of Heaven', 'tahun': '2013'},
    {'artis': 'My Chemical Romance', 'judul': 'Helena', 'tahun': '2004'},
    {'artis': 'Shinedown', 'judul': '45', 'tahun': '2003'},
    {'artis': 'Rise Against', 'judul': 'Prayer of the Refugee', 'tahun': '2006'},
    {'artis': 'Puddle of Mudd', 'judul': 'Blurry', 'tahun': '2001'},
    {'artis': 'Avenged Sevenfold', 'judul': 'Almost Easy', 'tahun': '2007'},
    {'artis': 'Evanescene', 'judul': 'My Immortal', 'tahun': '2003'},
    {'artis': 'Three Days Grace', 'judul': 'Never Too Late', 'tahun': '2006'},
    {'artis': 'Stone Sour', 'judul': 'Bother', 'tahun': '2002'},
    {'artis': 'Alter Bridge', 'judul': 'Blackbird', 'tahun': '2007'},
    {'artis': 'Seether', 'judul': 'Remedy', 'tahun': '2005'},
    {'artis': 'Skillet', 'judul': 'Hero', 'tahun': '2009'},
    {'artis': 'Bullet for My Valentine', 'judul': 'Waking the Demon', 'tahun': '2008'},
    {'artis': 'Papa Roach', 'judul': 'Scars', 'tahun': '2004'},
    {'artis': 'Three Days Grace', 'judul': 'Pain', 'tahun': '2006'},
    {'artis': 'Chevelle', 'judul': 'The Clincher', 'tahun': '2004'},
    {'artis': 'Breaking Benjamin', 'judul': 'So Cold', 'tahun': '2004'},
    {'artis': 'Theory of Deadman', 'judul': 'Rx (Medicate)', 'tahun': '2017'},
    {'artis': 'Godsmack', 'judul': 'Awake', 'tahun': '2000'},
    {'artis': 'Red Sun Shining', 'judul': 'Emotionless', 'tahun': '2015'},
    {'artis': 'Volbeat', 'judul': 'A Warrior\'s Call', 'tahun': '2010'},
    {'artis': 'Bad Wolves', 'judul': 'Zombie', 'tahun': '2018'},
    {'artis': 'Three Days Grace', 'judul': 'I Am an Animal', 'tahun': '2009'},
    {'artis': 'Stone Sour', 'judul': 'Absolute Zero', 'tahun': '2012'},
    {'artis': 'Seether', 'judul': 'Gasoline', 'tahun': '2002'},
    {'artis': 'Shinedown', 'judul': 'Save Me', 'tahun': '2005'},
    {'artis': 'My Darkest Days', 'judul': 'Porn Star Dancing', 'tahun': '2010'},
    {'artis': 'Black Stone Cherry', 'judul': 'Lonely Train', 'tahun': '2006'},
    {'artis': 'Avenged Sevenfold', 'judul': 'Hail to the King', 'tahun': '2013'},
    {'artis': 'Papa Roach', 'judul': 'Forever', 'tahun': '2006'},
    {'artis': 'The Pretty Reckless', 'judul': 'Make Me Wanna Die', 'tahun': '2010'},
    {'artis': 'Bring Me the Horizon', 'judul': 'Can You Feel My Heart', 'tahun': '2013'},
    {'artis': 'Slipknot', 'judul': 'Before I Forget', 'tahun': '2004'},
    {'artis': 'Pop Evil', 'judul': 'Trenches', 'tahun': '2013'},
    {'artis': 'Puddle of Mudd', 'judul': 'She Hates Me', 'tahun': '2001'},
    {'artis': 'Three Days Grace', 'judul': 'Riot', 'tahun': '2006'},
    {'artis': 'Skillet', 'judul': 'Whispers in the Dark', 'tahun': '2006'},
    {'artis': 'Seether', 'judul': 'Country Song', 'tahun': '2011'},
    {'artis': 'Papa Roach', 'judul': 'Getting Away with Murder', 'tahun': '2004'},
    {'artis': 'Chevelle', 'judul': 'Send the Pain Below', 'tahun': '2002'},
    {'artis': 'Seether', 'judul': 'Broken', 'tahun': '2002'},
    {'artis': 'Skillet', 'judul': 'Awake and Alive', 'tahun': '2009'},
    {'artis': 'Foo Fighters', 'judul': 'These Days', 'tahun': '2011'},
    {'artis': 'Five Finger Death Punch', 'judul': 'Wrong Side of Heaven', 'tahun': '2013'},
    {'artis': 'My Chemical Romance', 'judul': 'Helena', 'tahun': '2004'},
    {'artis': 'AC/DC', 'judul': 'Shot in the Dark', 'tahun': '2020'},
    {'artis': 'Bring Me the Horizon', 'judul': 'Parasite Eve', 'tahun': '2020'},
    {'artis': 'Five Finger Death Punch', 'judul': 'A Little Bit Off', 'tahun': '2020'},
    {'artis': 'Pop Evil', 'judul': 'Work', 'tahun': '2020'},
    {'artis': 'Seether', 'judul': 'Dangerous', 'tahun': '2020'},
    {'artis': 'Shinedown', 'judul': 'Atlas Falls', 'tahun': '2020'},
    {'artis': 'Three Days Grace', 'judul': 'Somebody That I Used to Know', 'tahun': '2020'},
    {'artis': 'Foo Fighters', 'judul': 'Shame Shame', 'tahun': '2020'},
    {'artis': 'The Pretty Reckless', 'judul': 'Death by Rock and Roll', 'tahun': '2021'},
    {'artis': 'Greta Van Fleet', 'judul': 'Heat Above', 'tahun': '2021'},
    {'artis': 'Architects', 'judul': 'Animals', 'tahun': '2021'},
    {'artis': 'Badflower', 'judul': 'Ghost', 'tahun': '2020'},
    {'artis': 'Evascence', 'judul': 'Use My Voice', 'tahun': '2020'},
    {'artis': 'Royal Blood', 'judul': 'Trouble\'s Coming', 'tahun': '2020'},
    {'artis': 'The Hu', 'judul': 'Wolf Totem (feat. Jacoby Shaddix)', 'tahun': '2020'},
    {'artis': 'Sevendust', 'judul': 'Blood From a Stone', 'tahun': '2020'},
    {'artis': 'Deftones', 'judul': 'Ohms', 'tahun': '2020'},
    {'artis': 'Papa Roach', 'judul': 'The Ending', 'tahun': '2020'},
    {'artis': 'Falling In Reverse', 'judul': 'Popular Monster', 'tahun': '2019'},
    {'artis': 'Machine Gun Kelly', 'judul': 'Bloody Valentine', 'tahun': '2020'},
    {'artis': 'Rise Against', 'judul': 'Nowhere Generation', 'tahun': '2021'},
    {'artis': 'Weezer', 'judul': 'All My Favorite Songs', 'tahun': '2021'},
    {'artis': 'The OFfspring', 'judul': 'Let The Bad Times Roll', 'tahun': '2021'},
    {'artis': 'The Pretty Reckless', 'judul': 'Only Love Can Save Me Now', 'tahun': '2021'},
    {'artis': 'Chevelle', 'judul': 'Self Destructor', 'tahun': '2021'},
    {'artis': 'Architects', 'judul': 'Dead Butterflies', 'tahun': '2021'},
    {'artis': 'Badflower', 'judul': '30', 'tahun': '2020'},
    {'artis': 'Royal Blood', 'judul': 'Typhoons', 'tahun': '2021'},
    {'artis': 'Evanescence', 'judul': 'Better Without You', 'tahun': '2021'},
    {'artis': 'The Hu', 'judul': 'Sad But True', 'tahun': '2020'},
    {'artis': 'Sevendust', 'judul': 'Dying to Live', 'tahun': '2020'},
    {'artis': 'Deftones', 'judul': 'Genesis', 'tahun': '2020'},
    {'artis': 'Papa Roach', 'judul': 'Kill the Noise', 'tahun': '2020'},
    {'artis': 'Falling in Reverse', 'judul': 'The Drug In Me Is Reimagined', 'tahun': '2020'},
    {'artis': 'Machine Gun Kelly', 'judul': 'My Ex\'s Best Friend (feat. Blackbear)', 'tahun': '2020'},
    {'artis': 'Rise Against', 'judul': 'Talking to Ourselves', 'tahun': '2021'},
    {'artis': 'Weezer', 'judul': 'Hero', 'tahun': '2020'},
    {'artis': 'The Offspring', 'judul': 'We Never Have Sex Anymore', 'tahun': '2021'},
    {'artis': 'The Pretty Reckless', 'judul': 'And So It Went (feat. Tom Morello)', 'tahun': '2021'},
    {'artis': 'Chevelle', 'judul': 'Peach', 'tahun': '2021'},
    {'artis': 'Royal Blood', 'judul': 'Limbo', 'tahun': '2021'},
    {'artis': 'Rise Against', 'judul': 'Sudden Urge', 'tahun': '2021'},
    {'artis': 'Chevelle', 'judul': 'Remember When', 'tahun': '2021'},
    {'artis': 'Weezer', 'judul': 'Grapes of Wrath', 'tahun': '2021'},
    {'artis': 'The Pretty Reckeless', 'judul': 'Only Love Can Save Me Now (feat. Matt Cameron and Kim Thayil)', 'tahun': '2021'},
    {'artis': 'The Offspring', 'judul': 'This Is Not Utopia', 'tahun': '2021'},
]

Pop=[
    {'artis': 'Tiara Andini', 'judul': 'Gemintang Hatiku', 'tahun': '2021', 'link' : 'https://youtu.be/qQtPAggFMt8'},
    {'artis': 'Tiara Andini', 'judul': 'Tega', 'tahun': '2023', 'link' : 'https://youtu.be/bLcRdYuS5xw'},
    {'artis': 'Tiara Andini', 'judul': 'Janji Setia', 'tahun': '2022', 'link' : 'https://youtu.be/PVIvHCX35hU'},
    {'artis': 'Tiara Andini', 'judul': 'Merasa Indah', 'tahun': '2022', 'link' : 'https://youtu.be/UHTVQVuVZTY'},
    {'artis': 'Tiara Andini', 'judul': 'Maafkan Aku', 'tahun': '2021', 'link' : 'https://youtu.be/bxEmsKYADl8'},
    {'artis': 'Tiara Andini', 'judul': 'Usai', 'tahun': '2023', 'link' : 'https://youtu.be/83ntBBDC8Xs'},
    {'artis': 'Tiara Andini', 'judul': 'Menjadi Dia', 'tahun': '2022', 'link' : 'https://youtu.be/8qoL-fhPfO8'},
    {'artis': 'Lyodra Ginting', 'judul': 'Ego', 'tahun': '2023', 'link' : 'https://youtu.be/vjYJrDDCOf0'},
    {'artis': 'Lyodra Ginting', 'judul': 'Gemintang Hatiku', 'tahun': '2020', 'link' : 'https://youtu.be/H_x8_LXwTW4'},
    {'artis': 'Lyodra Ginting', 'judul': 'Pesan Terakhir', 'tahun': '2022', 'link' : 'https://youtu.be/oaFj0lRi3gw'},
    {'artis': 'Lyodra Ginting', 'judul': 'Mengapa Kita', 'tahun': '2021', 'link' : 'https://youtu.be/Mc9WSGhPshE'},
    {'artis': 'Lyodra Ginting', 'judul': 'Tentang Kamu', 'tahun': '2021', 'link' : 'https://youtu.be/w3xBNrKJGQo'},
    {'artis': 'Lyodra Ginting', 'judul': 'Kalau Bosan', 'tahun': '2022', 'link' : 'https://youtu.be/rMePfW-C7bc'},
    {'artis': 'Lyodra Ginting', 'judul': 'Sabda Rindu', 'tahun': '2021', 'link' : 'https://youtu.be/o621gGw3dSU'},
    {'artis': 'Ziva Magnolya', 'judul': 'Pilihan Yang Terbaik', 'tahun': '2023', 'link' : 'https://youtu.be/0g9b7Mgm3oo'},
    {'artis': 'Ziva Magnolya', 'judul': 'Tak Sanggup Melupa', 'tahun': '2021', 'link' : 'https://youtu.be/BuU5dZb9W7o'},
    {'artis': 'Mahalini', 'judul': 'Sial', 'tahun': '2023', 'link' : 'https://youtu.be/QSWYyoF79oE'},
    {'artis': 'Mahalini', 'judul': 'Sisa Rasa', 'tahun': '2022', 'link' : 'https://youtu.be/Wh66ThpxvI4'},
    {'artis': 'Mahalini', 'judul': 'Kisah Sempurna', 'tahun': '2022', 'link' : 'https://youtu.be/8dgEh5crj0I'},
    {'artis': 'Mahalini', 'judul': 'Melawan Restu', 'tahun': '2021', 'link' : 'https://youtu.be/Svz5F8J1Ap0'},
    {'artis': 'Mahalini', 'judul': 'Bohongi Hati', 'tahun': '2023', 'link' : 'https://youtu.be/weG-sqHHCB8'},
    {'artis': 'Raim Laode', 'judul': 'Komang', 'tahun': '2023', 'link' : 'https://youtu.be/fKRtnMYMW08'},
    {'artis': 'Aruma', 'judul': 'Muak', 'tahun': '2023', 'link' : 'https://youtu.be/6r5Bj_7VPwE'},
    {'artis': 'Idgitaf', 'judul': 'Takut', 'tahun': '2022', 'link' : 'https://youtu.be/VJ1wfhlyWBw'},
    {'artis': 'Anggi Marito', 'judul': 'Tak Segampang Itu', 'tahun': '2023', 'link' : 'https://youtu.be/6NsiA6GFAbU'},
    {'artis': 'Once Mekel', 'judul': 'Symphony Yang Indah', 'tahun': '2016', 'link' : 'https://youtu.be/IzsOi_3TzM8'},
    {'artis': 'Payung Teduh', 'judul': 'Akad', 'tahun': '2018', 'link' : 'https://youtu.be/viW0M5R2BLo'},
    {'artis': 'JAZ', 'judul': 'Kasmaran', 'tahun': '2017', 'link' : 'https://youtu.be/4q24Qpn52CA'},
    {'artis': 'JAZ', 'judul': 'Teman Bahagia', 'tahun': '2018', 'link' : 'https://youtu.be/1XTLb0_6JDs'},
    {'artis': 'JAZ', 'judul': 'Dari Mata', 'tahun': '2016', 'link' : 'https://youtu.be/jieBCHsHg3A'},
    {'artis': 'GAC', 'judul': 'Bahagia', 'tahun': '2015', 'link' : 'https://youtu.be/zDHOW9PdQYE'},
    {'artis': 'GAC', 'judul': 'Cinta', 'tahun': '2016', 'link' : 'https://youtu.be/bkgfsvJvMSs'},
    {'artis': 'HIVI', 'judul': 'Remaja', 'tahun': '2018', 'link' : 'https://youtu.be/tUJAxxm1y1I'},
    {'artis': 'HIVI', 'judul': 'Pelangi', 'tahun': '2017', 'link' : 'https://youtu.be/bBjENsfyvFs'},
    {'artis': 'VIERRA', 'judul': 'Rasa Ini', 'tahun': '2010', 'link' : 'https://youtu.be/RpC8NVgIfnc'},
    {'artis': 'VIERRA', 'judul': 'Seandainya', 'tahun': '2011', 'link' : 'https://youtu.be/MofaZRiwiOw'},
    {'artis': 'VIERRA', 'judul': 'Kesepian', 'tahun': '2012', 'link' : 'https://youtu.be/ZNVQaiyv6zU'},
    {'artis': 'VIERRA', 'judul': 'Jadi Yang Kuinginkan', 'tahun': '2010', 'link' : 'https://youtu.be/4ofhlicIqD8'},
    {'artis': 'VIERRA', 'judul': 'Terlalu Lama', 'tahun': '2011', 'link' : 'https://youtu.be/NgQVLbD-lQ0'},
    {'artis': 'VIERRA', 'judul': 'Perih', 'tahun': '2010', 'link' : 'https://youtu.be/PqGmQiPQ0Tw'},
    {'artis': 'VIERRA', 'judul': 'Bersamamu', 'tahun': '2010', 'link' : 'https://youtu.be/9VFip4CQT8I'},
    {'artis': 'Sheila On 7', 'judul': 'Hari Bersamanya', 'tahun': '2011', 'link' : 'https://youtu.be/32M1DDVwqeY'},
    {'artis': 'Sheila On 7', 'judul': 'Dan', 'tahun': '2013', 'link' : 'https://youtu.be/dGcGbF4ex5o'},
    {'artis': 'Sheila On 7', 'judul': 'Seberapa Pantas', 'tahun': '2013', 'link' : 'https://youtu.be/OdDwIwoiZwU'},
    {'artis': 'Sheila On 7', 'judul': 'Film Favorit', 'tahun': '2018', 'link' : 'https://youtu.be/cHKZ7eWiZjM'},
    {'artis': 'Sheila On 7', 'judul': 'Melompat Lebih Tinggi', 'tahun': '2013', 'link' : 'https://youtu.be/ab9LL48USIU'},
    {'artis': 'Sheila On 7', 'judul': 'Pemuja Rahasia', 'tahun': '2013', 'link' : 'https://youtu.be/HvSW5Kap81o'},
    {'artis': 'Sheila On 7', 'judul': 'Sebuah Kisah Klasik', 'tahun': '2013', 'link' : 'https://youtu.be/WKsoUFblnfc'},
    {'artis': 'Dmasiv', 'judul': 'Cinta Ini Membunuhku', 'tahun': '2016', 'link' : 'https://youtu.be/iz7hDDlW8yQ'},
    {'artis': 'Dmasiv', 'judul': 'Diantara Kalian', 'tahun': '2009', 'link' : 'https://youtu.be/cQrSyOvRMzg'},
    {'artis': 'Dmasiv', 'judul': 'Merindukanmu', 'tahun': '2009', 'link' : 'https://youtu.be/e86Whn8TaMg'},
    {'artis': 'Dmasiv', 'judul': 'Cinta Sampai Disini', 'tahun': '2009', 'link' : 'https://youtu.be/NU2g0gXzkD0'},
    {'artis': 'Dmasiv', 'judul': 'Apa Salahku', 'tahun': '2011', 'link' : 'https://youtu.be/GuGgrnau8BA'},
    {'artis': 'Rossa', 'judul': 'Hijrah Cinta', 'tahun': '2014', 'link' : 'https://youtu.be/2DbHkjX-C1E'},
    {'artis': 'Rossa', 'judul': 'Aku Bukan Untukmu', 'tahun': '2012', 'link' : 'https://youtu.be/OK-DNdo5VWE'},
    {'artis': 'Rossa', 'judul': 'Tak Sanggup Lagi', 'tahun': '2013', 'link' : 'https://youtu.be/ALBIH1Z1W9Y'},
    {'artis': 'Rossa', 'judul': 'Pudar', 'tahun': '2012', 'link' : 'https://youtu.be/1Ny9z6cHTZc'},
    {'artis': 'Rossa', 'judul': 'Terlalu Cinta', 'tahun': '2012', 'link' : 'https://youtu.be/i3CYY6MSHIY'},
    {'artis': 'Rossa', 'judul': 'Takdir Cinta', 'tahun': '2012', 'link' : 'https://youtu.be/Jhdn3kyCUEQ'},
    {'artis': 'Rossa', 'judul': 'Hati Yang Kau Sakiti', 'tahun': '2012', 'link' : 'https://youtu.be/vY9vsQra-Kg'},
    {'artis': 'Rossa', 'judul': 'Jangan Hilangkan Dia', 'tahun': '2017', 'link' : 'https://youtu.be/wfDwfZblwVo'},
    {'artis': 'Rossa', 'judul': 'Ayat Ayat Cinta', 'tahun': '2012', 'link' : 'https://youtu.be/2zigf4LhZ1g'},
    {'artis': 'Rossa', 'judul': 'Tega', 'tahun': '2012', 'link' : 'https://youtu.be/pOVFWMR6tAM'},
    {'artis': 'Rossa', 'judul': 'Tegar', 'tahun': '2017', 'link' : 'https://youtu.be/dhy-mYfBN7Q'},
    {'artis': 'Tulus', 'judul': 'Nala', 'tahun': '2023', 'link' : 'https://youtu.be/7wGB30ijgqQ'},
    {'artis': 'Tulus', 'judul': 'Hati Hati Di Jalan', 'tahun': '2022', 'link' : 'https://youtu.be/9II3OGZETo4'},
    {'artis': 'Tulus', 'judul': 'Tujuh Belas', 'tahun': '2022', 'link' : 'https://youtu.be/cA7Gzh2ISL0'},
    {'artis': 'Tulus', 'judul': 'Monokrom', 'tahun': '2017', 'link' : 'https://youtu.be/QqJ-Vp8mvbk'},
    {'artis': 'Tulus', 'judul': 'Pamit', 'tahun': '2016', 'link' : 'https://youtu.be/G2-ZC9NpDBg'},
    {'artis': 'Tulus', 'judul': 'Teman Hidup', 'tahun': '2013', 'link' : 'https://youtu.be/dt4Ueda_h6Y'},
    {'artis': 'Tulus', 'judul': 'Jangan Cintai Aku Apa Adanya', 'tahun': '2015', 'link' : 'https://youtu.be/5L1RVCtL1D0'},
    {'artis': 'Tulus', 'judul': 'Sewindu', 'tahun': '2012', 'link' : 'https://youtu.be/wpst_4m_c-E'},
    {'artis': 'Tulus', 'judul': 'Gajah', 'tahun': '2015', 'link' : 'https://youtu.be/I-el8UadDc4'},
    {'artis': 'Tulus', 'judul': 'Sepatu', 'tahun': '2014', 'link' : 'https://youtu.be/DYbSp-B-8AM'},
    {'artis': 'Tulus', 'judul': 'Manusia Kuat', 'tahun': '2017', 'link' : 'https://youtu.be/f-fEeF12FH4'},
    {'artis': 'Tulus', 'judul': 'Ruang Sendiri', 'tahun': '2017', 'link' : 'https://youtu.be/c0p-61mLUGw'},
    {'artis': 'Raisa', 'judul': 'Jatuh Hati', 'tahun': '2015', 'link' : 'https://youtu.be/9gY0vpjbDuA'},
    {'artis': 'Raisa', 'judul': 'Usai Disini', 'tahun': '2018', 'link' : 'https://youtu.be/nqHFCV_3PxU'},
    {'artis': 'Raisa', 'judul': 'LDR', 'tahun': '2014', 'link' : 'https://youtu.be/sdPKH88gqjQ'},
    {'artis': 'Raisa', 'judul': 'Serba Salah', 'tahun': '2011', 'link' : 'https://youtu.be/NhefLOmwcdw'},
    {'artis': 'Raisa', 'judul': 'Lagu Untukmu', 'tahun': '2018', 'link' : 'https://youtu.be/q2PR9Ci8HNA'},
    {'artis': 'Raisa', 'judul': 'Apalah (Arti Menunggu)', 'tahun': '2012', 'link' : 'https://youtu.be/nx_kW1f5W6M'},
    {'artis': 'Raisa', 'judul': 'Kali Kedua', 'tahun': '2017', 'link' : 'https://youtu.be/SHj2kJzVi_g'},
    {'artis': 'Afgan', 'judul': 'Jodoh Pasti Bertemu', 'tahun': '2014', 'link' : 'https://youtu.be/MV_euZ_lKH8'},
    {'artis': 'Afgan', 'judul': 'Bawalah Cintaku', 'tahun': '2013', 'link' : 'https://youtu.be/CPENPhizI-U'},
    {'artis': 'Afgan', 'judul': 'Terima Kasih Cinta', 'tahun': '2013', 'link' : 'https://youtu.be/Hr0AAqHLLSg'},
    {'artis': 'Afgan', 'judul': 'Sadis', 'tahun': '2013', 'link' : 'https://youtu.be/f45peONgdIY'},
    {'artis': 'Afgan', 'judul': 'Kunci Hati', 'tahun': '2017', 'link' : 'https://youtu.be/JYlAdZkpWIQ'},
    {'artis': 'Afgan', 'judul': 'Bukan CInta Biasa', 'tahun': '2013', 'link' : 'https://youtu.be/nshdkoeu_fY'},
    {'artis': 'Judika', 'judul': 'Aku Yang Terluka', 'tahun': '2023', 'link' : 'https://youtu.be/qfdRBWYZWlc'},
    {'artis': 'Judika', 'judul': 'Tak Mungkin Bersama', 'tahun': '2020', 'link' : 'https://youtu.be/H-GZ5wu2ufU'},
    {'artis': 'Judika', 'judul': 'Bagaimana Kalau Aku Tidak Baik Baik Saja', 'tahun': '2022', 'link' : 'https://youtu.be/Psr7yfO_WY0'},
    {'artis': 'Judika', 'judul': 'Bukan Dia Tapi Aku', 'tahun': '2012', 'link' : 'https://youtu.be/IfPCRfaQBA0'},
    {'artis': 'Judika', 'judul': 'Putus Atau Terus', 'tahun': '2021', 'link' : 'https://youtu.be/47SpkXg_sYY'},
    {'artis': 'Judika', 'judul': 'Jikalau Kau Cinta', 'tahun': '2018', 'link' : 'https://youtu.be/4Xi9hlJhfOw'},
    {'artis': 'Judika', 'judul': 'Cinta Karena Cinta', 'tahun': '2020', 'link' : 'https://youtu.be/FZjk56FfdJY'},
    {'artis': 'Judika', 'judul': 'Aku Yang Tersakiti', 'tahun': '2012', 'link' : 'https://youtu.be/9tZPmSv6DTs'},
    {'artis': 'Judika', 'judul': 'Jadi Aku Sebentar Saja', 'tahun': '2017', 'link' : 'https://youtu.be/Oo9BsGPWWV0'},
    {'artis': 'Judika', 'judul': 'Mama Papa Larang', 'tahun': '2013', 'link' : 'https://youtu.be/lY7T8Mz-18s'},
    {'artis': 'Judika', 'judul': 'Malaikat', 'tahun': '2014', 'link' : 'https://youtu.be/p8IbIHTFppI'},
    {'artis': 'Andmesh Kamaleng', 'judul': 'Jangan Rubah Takdirku', 'tahun': '2018', 'link' : 'https://youtu.be/hPJpNXL7WXo'},
    {'artis': 'Andmesh Kamaleng', 'judul': 'Kumau Dia', 'tahun': '2020', 'link' : 'https://youtu.be/ihSQUBV_X1k'},
    {'artis': 'Andmesh Kamaleng', 'judul': 'Hanya Rindu', 'tahun': '2019', 'link' : 'https://youtu.be/CJC5PY5erzI'},
    {'artis': 'Andmesh Kamaleng', 'judul': 'Sampai Tua Nanti', 'tahun': '2021', 'link' : 'https://youtu.be/cfYhBLDWlvw'},
    {'artis': 'Andmesh Kamaleng', 'judul': 'Cinta Luar Biasa', 'tahun': '2019', 'link' : 'https://youtu.be/FcOctsNXyjk'},
    {'artis': 'Andmesh Kamaleng', 'judul': 'Senyumlah', 'tahun': '2021', 'link' : 'https://youtu.be/Cs8wtborzRU'},
    {'artis': 'Andmesh Kamaleng', 'judul': 'Bisa Tanpamu', 'tahun': '2022', 'link' : 'https://youtu.be/deaNzyAZhHw'},
    {'artis': 'Andmesh Kamaleng', 'judul': 'Tiba Tiba', 'tahun': '2021', 'link' : 'https://youtu.be/V16PvIA6k14'},
    {'artis': 'Andmesh Kamaleng', 'judul': 'Anugerah Terindah', 'tahun': '2023', 'link' : 'https://youtu.be/o25_Tn8BnFM'},
    {'artis': 'Bunga Citra Lestari', 'judul': 'Karena Kucinta Kau', 'tahun': '2013', 'link' : 'https://youtu.be/yYfPmWtU17U'},
    {'artis': 'Bunga Citra Lestari', 'judul': 'Cinta Sejati', 'tahun': '2013', 'link' : 'https://youtu.be/Bgt9g1q-xj0'},
    {'artis': 'Bunga Citra Lestari', 'judul': 'Kecewa', 'tahun': '2013', 'link' : 'https://youtu.be/173tZuk_2lY'},
    {'artis': 'Tiara Andini', 'judul': 'Janji Setia', 'tahun': '2022', 'link' : 'https://youtu.be/PVIvHCX35hU'}
]

Kpop=[
    {'artis': 'BTS', 'judul': 'Dynamite', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=gdZLi9oWNZg'},
    {'artis': 'BLACKPINK', 'judul': 'How You Like That', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=ioNng23DkIM'},
    {'artis': 'PSY', 'Judul': 'Gangnam Style', 'tahun': '2012', 'link' : 'https://www.youtube.com/watch?v=9bZkp7q19f0'},
    {'artis': 'Twice', 'Judul': 'Fancy', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=kOHB85vDuow'},
    {'artis': 'BLACKPINK', 'Judul': 'Kill This Love', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=2S24-y0Ij3Y'},
    {'artis': 'iKON', 'Judul': 'Love Scenario', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=vecSVX1QYbQ'},
    {'artis': 'ITZY', 'Judul': 'Not Shy', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=wTowEKjDGkU'},
    {'artis': 'BTS', 'Judul': 'Blood Sweet Tears', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=hmE9f-TEutc'},
    {'artis': 'Red Velvet', 'Judul': 'Red Flavor', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=WyiIGEHQP8o'},
    {'artis': 'BTS', 'judul': 'Permission To Dance', 'tahun': '2018', 'link' :'https://www.youtube.com/watch?v=CuklIb9d3fI'},
    {'artis': 'BTS', 'judul': 'Boy With Luv', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=XsX3ATc3FbA'},
    {'artis': 'BLACKPINK', 'judul': 'DDU-DU DDU-DU', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=IHNzOHi8sJs'},
    {'artis': 'BTS', 'judul': 'Spring Day', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=xEeFrLSkMm8'},
    {'artis': 'Girls Generation', 'judul': 'Gee', 'tahun': '2009', 'link' : 'https://www.youtube.com/watch?v=U7mPqycQ0tQ'},
    {'artis': 'BTS', 'judul': 'Mic Drop', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=kTlv5_Bs8aw'},
    {'artis': 'BTS', 'Judul': 'DNA', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=MBdVXkSdhwU'},
    {'artis': 'BTS', 'judul': 'I Need U', 'tahun': '2015', 'link' : 'https://www.youtube.com/watch?v=jjskoRh8GTE'},
    {'artis': 'EXO', 'judul': 'Love Shot', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=pSudEWBAYRE'},
    {'artis': 'Red Velvet', 'judul': 'Bad Boy', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=J_CFBjAyPWE'},
    {'artis': 'ITZY', 'judul': 'Wannabe', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=fE2h3lGlOsk'},
    {'artis': 'BLACKPINK', 'judul': 'Lovesick Girls', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=dyRsYk0LyA8'},
    {'artis': 'Chanyeol & punch', 'judul': 'Spring is Gone by Chance', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=GjyMuHmzxVE'},
    {'artis': 'BTS', 'judul': 'N.O', 'tahun': '2013', 'link' : 'https://www.youtube.com/watch?v=mmgxPLLLyVo'},
    {'artis': 'TWICE', 'judul': 'Cheer Up', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=c7rCyll5AeY'},
    {'artis': 'BTS', 'judul': 'Not Today', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=9DwzBICPhdM'},
    {'artis': 'EXO', 'judul': 'Monster', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=KSH-FVVtTf0'},
    {'artis': 'BTS', 'judul': 'Fire', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=ALj5MKjy2BU'},
    {'artis': 'IU ft. G-Dragon', 'judul': 'palette', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=d9IxdwEFk1c'},
    {'artis': 'BTS', 'judul': 'MIC Drop (Steve Aoki Remix)', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=kTlv5_Bs8aw'},
    {'artis': 'Wanna One', 'judul': 'Energetic', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=EVaV7AwqBWg'},
    {'artis': 'BTS', 'judul': 'Fake Love', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=7C2z4GqqS5E'},
    {'artis': 'TWICE', 'judul': 'Feel Special', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=3ymwOvzhwHs'},
    {'artis': 'BLACKPINK', 'judul': 'As If Its Your Last', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=Amq-qlqbjYA'},
    {'artis': 'Red Velvet', 'judul': 'Psycho', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=uR8Mrt1IpXg'},
    {'artis': 'EXO', 'judul': 'Tempo', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=iwd8N6K-sLk'},
    {'artis': 'IU', 'judul': 'Blueming', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=D1PvIWdJ8xo'},
    {'artis': 'Stray Kids', 'judul': 'Gods Menu', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=TQTlCHxyuu8'},
    {'artis': 'MAMAMOO', 'judul': 'Hip', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=KhTeiaCezwM'},
    {'artis': 'WAYV', 'judul': 'Kick Back', 'tahun': '2021', 'link' : 'https://www.youtube.com/results?search_query=kick+back+nct'},
    {'artis': 'GOT7', 'judul': 'Just Right', 'tahun': '2015', 'link' : 'https://www.youtube.com/watch?v=vrdk3IGcau8'},
    {'artis': 'TWICE', 'judul': 'Likey', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=V2hlQkVJZhE'},
    {'artis': 'Red Velvet', 'judul': 'Russian Roulette', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=QslJYDX3o8s'},
    {'artis': 'EXO', 'judul': 'Ko Ko Bop', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=IdssuxDdqKk'},
    {'artis': 'IU', 'judul': 'Good Day', 'tahun': '2010', 'link' : 'https://www.youtube.com/watch?v=jeqdYqsrsA0'},
    {'artis': 'Stray Kids', 'judul': 'My Pace', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=pok5yDw77uM'},
    {'artis': 'MAMAMOO', 'judul': 'Starry Night', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=LjUXm0Zy_dk'},
    {'artis': 'NCT', 'judul': 'Boss', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=0AUFyFEt35g'},
    {'artis': 'GOT7', 'judul': 'Hard Carry', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=O57jr1oZDIw'},
    {'artis' : 'BTS', 'judul' : 'Lie', 'tahun' : '2017', 'link' : 'https://www.youtube.com/watch?v=omzjKIgeJGs'},
    {'artis' : 'BTS', 'judul' : 'Mama', 'tahun' : '2017', 'link' : 'https://www.youtube.com/watch?v=nVHcXZK7pKs'},
    {'artis': 'Red Velvet', 'judul': 'Peek A boo', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=6uJf2IT2Zh8'},
    {'artis': 'Red Velvet', 'judul': 'Feel My Rhythm', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=R9At2ICm4LQ'},
    {'artis': 'Red Velvet', 'judul': 'Queendom', 'tahun': '2021', 'link' : 'https://www.youtube.com/watch?v=c9RzZpV460k'},
    {'artis': 'Red Velvet', 'judul': 'Zim Zalabim', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=YBnGBb1wg98'},
    {'artis': 'Red Velvet', 'judul': 'Happiness', 'tahun': '2014', 'link' : 'https://www.youtube.com/watch?v=JFgv8bKfxEs'},
    {'artis': 'Red Velvet', 'judul': 'you better know', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=qF6wlRu9S9E'},
    {'artis': 'Red Velvet', 'judul': 'Oh Boy', 'tahun': '2015', 'link' :'https://www.youtube.com/watch?v=3PgGuUP8_jI'},
    {'artis': 'Red Velvet', 'judul': 'Power Up', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=aiHSVQy9xN8'},
    {'artis': 'Red Velvet', 'judul': 'Dumb Dumb ', 'tahun': '2015', 'link' : 'https://www.youtube.com/watch?v=XGdbaEDVWp0'},
    {'artis': 'Red Velvet', 'judul': 'Would U', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=XGdbaEDVWp0'},
    {'artis': 'BTS', 'Judul': 'Run', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=ssD6mzewGVo'},
    {'artis': 'BTS', 'Judul': 'Dope', 'tahun': '2012', 'link' : 'https://www.youtube.com/watch?v=BVwAVbKYYeM'},
    {'artis': 'BTS', 'Judul': 'Anpanman', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=EFHeeRIDAsg'},
    {'artis': 'BTS', 'Judul': 'Where You from', 'tahun': '2014', 'link' : 'https://www.youtube.com/watch?v=cicyjCWzrRw'},
    {'artis': 'BTS', 'Judul': 'save me', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=GZjt_sA2eso'},
    {'artis': 'BTS', 'Judul': 'Converse High', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=jw-pAvTfPFY'},
    {'artis': 'BTS', 'Judul': 'Born singer', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=TbjUXK2M5n8'},
    {'artis': 'BTS', 'Judul': 'lost', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=-YIj6H4ShQA'},
    {'artis': 'BTS', 'Judul': 'Begin', 'tahun': '2016', 'link' : 'https://www.youtube.com/watch?v=-YIj6H4ShQA'},
    {'artis': 'BLACKPINK', 'Judul': 'Playing With Fire', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=9pdj4iJD08s'},
    {'artis': 'BLACKPINK', 'Judul': 'Boombayah', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=bwmSjveL3Lc'},
    {'artis': 'BLACKPINK', 'Judul': 'Stay', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=FzVR_fymZw4'},
    {'artis': 'BLACKPINK', 'Judul': 'pink venom', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=gQlMMD8auMs'},
    {'artis': 'BLACKPINK', 'Judul': 'Whistle', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=dISNgvVpWlo'},
    {'artis': 'BLACKPINK', 'Judul': 'REALLY', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=He322O1JWgU'},
    {'artis': 'BLACKPINK', 'Judul': 'SEE U LATER', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=fpimnj4SNjQ'},
    {'artis': 'BLACKPINK', 'Judul': 'KICK IT', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=-gZC9hC1PDQ'},
    {'artis': 'BLACKPINK', 'Judul': 'HOPE NOT', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=l6zMnMMzsss'},
    {'artis': 'BLACKPINK', 'Judul': 'FOREVER YOUNG', 'tahun': '2019', 'link' : 'https://www.youtube.com/watch?v=-gibBYpzZbI'},
    {'artis': 'BLACKPINK', 'Judul': 'Tally', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=VQo4hyWfBQ4'},
    {'artis': 'BLACKPINK', 'Judul': 'Shut Down', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=NpVJidAKOqc'},
    {'artis': 'BLACKPINK', 'Judul': 'Ready For Love', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=-Wduzor_Y1Q'},
    {'artis': 'BLACKPINK', 'Judul': 'The Happiest Girl', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=kVXazE8wR1Q'},
    {'artis': 'BLACKPINK', 'Judul': 'ice cream', 'tahun': '2020', 'link' : 'https://www.youtube.com/watch?v=vRXZj0DzXIA' },
    {'artis': 'BLACKPINK', 'Judul': 'Hard To Love', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=7Hr3p1BHC_E'},
    {'artis': 'BLACKPINK', 'Judul': 'Typa girl', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=z9tifvQSu-g'},
    {'artis': 'BLACKPINK', 'Judul': 'Yeah Yeah Yeah', 'tahun': '2022', 'link' : 'https://www.youtube.com/watch?v=wQTjv-Xo1gY'},
    {'artis': 'EXO', 'judul': 'Gravity', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=prFir9hRSxU&pp=ygULZ3Jhdml0eSBleG8%3D'},
    {'artis': 'EXO', 'judul': 'Sign', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=ig1D5DVP5MY'},
    {'artis': 'EXO', 'judul': 'Damage', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=hPSw9NHc-dk'},
    {'artis': 'EXO', 'judul': 'ooh la la', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=7XVPxbZ_C9Q'},
    {'artis': 'EXO', 'judul': 'Smile On Face', 'tahun': '2018', 'link' : 'https://www.youtube.com/watch?v=ghMmJgAos3Q'},
    {'artis': 'EXO', 'judul': 'Touch It', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=yiHe_eWOUfM'},
    {'artis': 'EXO', 'judul': 'The Eve', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=b6ycw7p9-bE'},
    {'artis': 'EXO', 'judul': 'Chill', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=KD9k2kYr6gY'},
    {'artis': 'EXO', 'judul': 'Going Crazy', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=ush0XGzx-oQ'},
    {'artis': 'EXO', 'judul': 'Diamond', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=9BwLMq7Wn2I'},
    {'artis': 'EXO', 'judul': 'Forever', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=A_V7VGgi5b0'},
    {'artis': 'EXO', 'judul': 'Walk on Memories', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=rUbOiD192iU'},
    {'artis': 'EXO', 'judul': 'What U Do?', 'tahun': '2017', 'link' : 'https://www.youtube.com/watch?v=FMPzSr8Qlts'},
    {'artis': 'EXO', 'judul': 'XOXO', 'tahun': '2013', 'link' : 'https://www.youtube.com/watch?v=6UmIrGfY1k8'},
    {'artis': 'EXO', 'judul': 'Baby dont cry', 'tahun': '2013', 'link' : 'https://www.youtube.com/watch?v=-poEUTl0wHE'},
    {'artis': 'EXO', 'judul': 'Dont go', 'tahun': '2013', 'link' : 'https://www.youtube.com/watch?v=9nkIxVcBHCQ'},
    {'artis': 'EXO', 'judul': 'Lucky', 'tahun': '2013', 'link' : 'https://www.youtube.com/watch?v=lsrVF1J4emc'},
    {'artis': 'EXO', 'judul': 'No Matter', 'tahun': '2021', 'link' : 'https://www.youtube.com/watch?v=SsWnx3OeNZs'},
    {'artis': 'EXO', 'judul': 'Paradise', 'tahun': '2021', 'link' : 'https://www.youtube.com/watch?v=YFrjy7uAS48'},
    {'artis': 'EXO', 'judul': 'Dont Fight The Feeling', 'tahun': '2021', 'link' : 'https://www.youtube.com/watch?v=2IkoKhr6Tss'},
    {'artis': 'EXO', 'judul': 'Just As Usual', 'tahun': '2021', 'link' : 'https://www.youtube.com/watch?v=cNnY5hVGi4Y'},
    {'artis': 'EXO', 'judul': 'Runaway', 'tahun': '2013', 'link' : 'https://www.youtube.com/watch?v=N4Cuqcpc6qU'}
]
